fb_admins: "1227210274"
twitter_username: chibicode
cover_image: "fuji.jpg"

markdown: redcarpet
pygments: true
permalink: :title
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

locale: en
exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Procfile"
  - "Gruntfile.coffee"
  - "bower.json"
  - "package.json"
  - "node_modules"
  - "config.json"
  - "en"

locale: ja
