title: "Shu Uesugi"
description: "Hacker."
google_analytics: "UA-32987822-1"
fb_admins: "1227210274"
twitter_username: chibicode
locale: en

markdown: redcarpet
pygments: true
permalink: :title
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Procfile"
  - "Gruntfile.coffee"
  - "bower.json"
  - "package.json"
  - "node_modules"
  - "config.json"
